### ISSUE TITLE
Arch Linux last release.

### ISSUE THREAD

**Issue by piny4man** [slimbook/slimbookamdcontroller#24]
After updating to the last AUR package update, I am not able to launch the controller. I receive this error from command line.
 ```bash
/usr/share/slimbookamdcontroller/src
Traceback (most recent call last):
  File "/usr/bin/slimbookamdcontroller", line 35, in <module>
    from slimbookamdcontroller import SlimbookAMD
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 6, in <module>
    from sections.gpu_section import GpuSection
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 21, in <module>
    class GpuSection():
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 150, in GpuSection
    def __render_chart(self, gpu: GpuService) -> FigureCanvas:
NameError: name 'GpuService' is not defined
 ```

It is impossible to make it work now. Thanks in advance

**Comment by MarSlimbook** [comment]
I've tried it in Manjaro, and AUR installation goes well (apart from a python-matplotlib dependency)...
I'm not sure why this happens, the version I installed is 0.3.9beta-1 is this correct?
Does `/usr/share/slimbookamdcontroller/src/services/gpu_service.py` exist?
Try removing and reinstalling the app, and check the installation output.
If the problem remains I'll try to test it in your distro.

**Comment by UbayGD** [comment]
Is it possible that it fails just in that line since it is where only GpuService is used as type?

In the rest of the file it is used inside methods and functions that, having failed the import, never get to use the GpuService.

But the normal thing is that the import should not fail :)
